// GENERATED from official-source research (NY.prep.json) — do not hand-edit rates here
// without updating the source + asOf on the line. Level: county+municipality. Local table complete: False.
// Local-level source: NYS DTF Mortgage recording tax page + MT-15; NY Tax Law Articles 31-A-1…31-K, 33-B, §§1205–1206 (enabling acts); county clerk pages (https://www.tax.ny.gov/pit/mortgage/mtgidx.htm) as of 2025-12-30.
import type { LocalTaxTable, TaxLineItem, SourceRef } from "../closingCostTypes";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _T = TaxLineItem;

const S0 = "NYS DTF Form MT-15 (1/25) Mortgage Recording Tax Return — rate tables 1–5";
const S1 = "https://www.tax.ny.gov/pdf/current_forms/mortgage/mt15.pdf";
const S2 = "NYC Dept of Finance — Real Property Transfer Tax (RPTT)";
const S3 = "https://www.nyc.gov/site/finance/property/property-real-property-transfer-tax-rptt.page";
const S4 = "NYS Dept of Taxation & Finance — Real estate transfer tax";
const S5 = "https://www.tax.ny.gov/bus/transfer/rptidx.htm";
const S6 = "Broome County Clerk — Deed FAQs";
const S7 = "https://www.broomecountyny.gov/clerk/DeedFAQs";
const S8 = "Columbia County Clerk — Fees List ('County Tax: $2 per $1000')";
const S9 = "https://www.columbiacountyny.gov/289/Fees-List";
const S10 = "Cortland County Clerk — Real Property page + 'Calculations - Deeds and Mortgages' workbook ('Transfer Tax - County ($2 per $1,000)')";
const S11 = "https://www.cortlandcountyny.gov/177/Real-Property";
const S12 = "Madison County Local Law No. 5 of 2025 (filed with NYS DOS 8/21/2025) + County Clerk page";
const S13 = "https://www.madisoncounty.ny.gov/DocumentCenter/View/26078/Local-Law-No-5-of-2025-Authorizing-Real-Estate-Transfer-Tax";
const S14 = "Tompkins County Clerk — Land Services ('Transfer Tax: $6/per $1000' = $4 state + $2 county) ; Tax Law Art. 31-G §1449-bbbbb";
const S15 = "https://www.tompkinscountyny.gov/All-Departments/County-Clerk/Land-Services";
const S16 = "City of Yonkers — Real Estate Transfer Tax";
const S17 = "https://www.yonkersny.gov/257/Real-Estate-Transfer-Tax";
const S18 = "City of Mount Vernon Comptroller — 'Implementation of Revised Real Property Transfer Tax Requirements, Effective for Deeds Dated On or After February 1, 2026' (copy hosted by Judicial Title) + City RPTT return (rev. 1/04/24, Code ch. 234)";
const S19 = "https://www.judicialtitle.com/pdf/tjn/Mt_Vernon_Transfer_Tax_Implementation_of_New_Requirements.pdf";
const S20 = "City of Peekskill RPTT return (Code ch. 521; form copy hosted by Langdon Title) + Tax Law §1206";
const S21 = "https://langdontitle.com/wp-content/uploads/2022/05/City-of-Peekskill-Transfer-Tax-Form.pdf";
const S22 = "Suffolk County Clerk — Peconic Bay Region Community Preservation Fund form (Rev 12/12/2023)";
const S23 = "https://suffolkcountyny.gov/Portals/0/formsdocs/clerk/Forms/Recording/PeconicBayRegion_Fill_in_Rev121223.pdf";
const S24 = "Town of Warwick CPF Transfer Tax form (rev 4) — filed with Orange County Clerk; Tax Law Art. 31-F";
const S25 = "https://townofwarwickny.gov/wp-content/uploads/2019/04/cpf_tax_form_rev4.pdf";
const S26 = "Dutchess County Clerk — Forms & Guidebooks (Red Hook Transfer Tax Return) + Red Hook form (LL 1 of 2007; Tax Law Art. 31-A-1)";
const S27 = "https://www.dutchessny.gov/Departments/County-Clerk/County-Clerk-Forms-and-Guidebooks.htm";
const S28 = "Ulster County Clerk — Recording a Deed (local transfer taxes)";
const S29 = "https://clerk.ulstercountyny.gov/countyclerk/land-records/recording-deed";
const S30 = "Columbia County Clerk page + Town of Chatham transfer-tax page (LL 7 of 2023; Tax Law Art. 31-A-2*2); median from NYS DTF residential median table";
const S31 = "https://www.chathamnewyork.us/new__chatham_transfer_tax/index.php";
const F0 = (rate: number, notes?: string): TaxLineItem => ({ name: "Peconic Bay Region CPF 2% + Community Housing Fund 0.5% (commercial)", rate, base: "price", party: "buyer", source: S22, sourceUrl: S23, asOf: "2023-04-01", ...(notes ? { notes } : {}) });

export const NY_LOCAL_LEVEL = "county+municipality" as const;
export const NY_LOCAL_LEVEL_SOURCE: SourceRef & { statement: string } = {
  source: "NYS DTF Mortgage recording tax page + MT-15; NY Tax Law Articles 31-A-1…31-K, 33-B, §§1205–1206 (enabling acts); county clerk pages", sourceUrl: "https://www.tax.ny.gov/pit/mortgage/mtgidx.htm", asOf: "2025-12-30",
  statement: "MRT varies by COUNTY (plus a Yonkers city add-on) per MT-15. Local transfer taxes exist only where a special state enabling act was used: county-wide taxes (Broome, Columbia, Cortland, Madison, Tompkins), city taxes (NYC, Yonkers, Mount Vernon, Peekskill, Kingston) and town CPF taxes (5 Peconic Bay towns; Hudson Valley towns Red Hook, Warwick, New Paltz, Gardiner, Marbletown, Rochester, Chatham). Every other locality: state 0.4% only.",
};

export const NY_LOCAL: LocalTaxTable = {
  countyAbsentMeansNone: false,
  muniAbsentMeansNone: true,
  entries: [
  { id: "ny-albany-county", kind: "county", name: "Albany County", county: "Albany County", lines: [
      { name: "Mortgage Recording Tax — Albany (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-allegany-county", kind: "county", name: "Allegany County", county: "Allegany County", lines: [
      { name: "Mortgage Recording Tax — Allegany (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-bronx-county", kind: "county", name: "Bronx County", county: "Bronx County", match: ["bronx", "the bronx"], lines: [
      { name: "NYC Real Property Transfer Tax — commercial (all other transfers)", rate: 0.02625, tiers: [{ over: 0, rate: 0.01425 }, { over: 500000, rate: 0.02625 }], base: "price", party: "seller", source: S2, sourceUrl: S3, asOf: "2026-09-24", notes: "NYC DOF: 'All other transfers: If the value is $500,000 or less, the rate is 1.425% of the price. If the value is more than $500,000 the rate is 2.625%.' Cliff — the bracket rate applies to the WHOLE price. Grantor (seller) pays." },
      { name: "NYS additional base tax — NYC non-residential ≥ $2M (Tax Law §1402(b))", rate: 0.0025, tiers: [{ over: 0, rate: 0 }, { over: 1999999.99, rate: 0.0025 }], base: "price", party: "seller", source: S4, sourceUrl: S5, asOf: "2025-12-30", notes: "DTF: from 7/1/2019, 'An additional base tax of $1.25 for each $500 ... when the consideration for the entire conveyance of property other than residential real property is $2 million or more' (NYC only). Cliff at $2,000,000 on the whole consideration (modeled as over 1,999,999.99 because the test is '$2M or more'). Seller pays (same as base tax). With the 0.4% state base tax the state total in NYC is 0.65% on commercial ≥ $2M. The residential version starts at $3M and the residential 'supplemental' 0.25%–2.9% tax is residential-only (not modeled)." },
      { name: "Mortgage Recording Tax — NYC (commercial)", rate: 0.028, tiers: [{ over: 0, rate: 0.0205 }, { over: 499999.99, rate: 0.028 }], base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 4: all mortgages < $500,000 = $2.05/$100 (NYC 1.00 + basic 0.50 + special additional 0.25 + MCTD additional 0.30); 'All other mortgages securing $500,000 or more' = $2.80/$100 (NYC 1.75 + 0.50 + 0.25 + 0.30). Cliff on whole loan amount at $500,000 (modeled as over 499,999.99 because the test is '$500,000 or more'). (1–3 family / residential condo ≥$500K = 2.175%, not applicable.) Borrower pays on commercial." }
    ] },
  { id: "ny-broome-county", kind: "county", name: "Broome County", county: "Broome County", lines: [
      { name: "Mortgage Recording Tax — Broome (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." },
      { name: "Broome County real estate transfer tax", rate: 0.001, base: "price", party: "seller", source: S6, sourceUrl: S7, asOf: "2026-09-24", notes: "Clerk: 'Transfer Tax in Broome County is $5 per $1000. $4 goes to the State / $1 goes to Broome County.' County portion = $0.50 per $500 (Tax Law §1449-g, Art. 31-C). Paid by grantor (§1449-i). Flat on whole consideration; no commercial exemption (only a <$200K personal-residence option/contract exemption)." }
    ] },
  { id: "ny-cattaraugus-county", kind: "county", name: "Cattaraugus County", county: "Cattaraugus County", lines: [
      { name: "Mortgage Recording Tax — Cattaraugus (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-cayuga-county", kind: "county", name: "Cayuga County", county: "Cayuga County", lines: [
      { name: "Mortgage Recording Tax — Cayuga (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-chautauqua-county", kind: "county", name: "Chautauqua County", county: "Chautauqua County", lines: [
      { name: "Mortgage Recording Tax — Chautauqua (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-chemung-county", kind: "county", name: "Chemung County", county: "Chemung County", lines: [
      { name: "Mortgage Recording Tax — Chemung (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-chenango-county", kind: "county", name: "Chenango County", county: "Chenango County", lines: [
      { name: "Mortgage Recording Tax — Chenango (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-clinton-county", kind: "county", name: "Clinton County", county: "Clinton County", lines: [
      { name: "Mortgage Recording Tax — Clinton (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-columbia-county", kind: "county", name: "Columbia County", county: "Columbia County", lines: [
      { name: "Mortgage Recording Tax — Columbia (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.50% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." },
      { name: "Columbia County real estate transfer tax", rate: 0.002, base: "price", party: "seller", source: S8, sourceUrl: S9, asOf: "2026-09-24", notes: "Clerk fee schedule: 'Doc Stamps: $4 per $1,000 County Tax: $2 per $1000'. Authorized by Tax Law Art. 31-A-2 §1439-b ($1 per $500; first $150,000 of a single-family residence exempt — residential only). Paid by grantor (§1439-d). Enabling article is scheduled for repeal 12/31/2027 — re-verify after that date." }
    ] },
  { id: "ny-cortland-county", kind: "county", name: "Cortland County", county: "Cortland County", lines: [
      { name: "Mortgage Recording Tax — Cortland (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." },
      { name: "Cortland County real estate transfer tax", rate: 0.002, base: "price", party: "seller", source: S10, sourceUrl: S11, asOf: "2023-11-17", notes: "Clerk: 'Effective November 17, 2023 an additional Transfer Tax is applicable to conveyances'; clerk calculator: County $2 per $1,000. Authorized by Tax Law Art. 31-I (§1449-bbbbbbb: $1 per $500). Paid by grantor (§1449-ddddddd). Enabling article repealed 10/25/2030." }
    ] },
  { id: "ny-delaware-county", kind: "county", name: "Delaware County", county: "Delaware County", lines: [
      { name: "Mortgage Recording Tax — Delaware (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-dutchess-county", kind: "county", name: "Dutchess County", county: "Dutchess County", lines: [
      { name: "Mortgage Recording Tax — Dutchess (commercial)", rate: 0.0105, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.05% of principal debt (basic 0.50% + special additional 0.25% + MCTD additional 0.30%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-erie-county", kind: "county", name: "Erie County", county: "Erie County", lines: [
      { name: "Mortgage Recording Tax — Erie (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-essex-county", kind: "county", name: "Essex County", county: "Essex County", lines: [
      { name: "Mortgage Recording Tax — Essex (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-franklin-county", kind: "county", name: "Franklin County", county: "Franklin County", lines: [
      { name: "Mortgage Recording Tax — Franklin (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-fulton-county", kind: "county", name: "Fulton County", county: "Fulton County", lines: [
      { name: "Mortgage Recording Tax — Fulton (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-genesee-county", kind: "county", name: "Genesee County", county: "Genesee County", lines: [
      { name: "Mortgage Recording Tax — Genesee (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-greene-county", kind: "county", name: "Greene County", county: "Greene County", lines: [
      { name: "Mortgage Recording Tax — Greene (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.50% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-hamilton-county", kind: "county", name: "Hamilton County", county: "Hamilton County", lines: [
      { name: "Mortgage Recording Tax — Hamilton (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-herkimer-county", kind: "county", name: "Herkimer County", county: "Herkimer County", lines: [
      { name: "Mortgage Recording Tax — Herkimer (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-jefferson-county", kind: "county", name: "Jefferson County", county: "Jefferson County", lines: [
      { name: "Mortgage Recording Tax — Jefferson (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-kings-county", kind: "county", name: "Kings County", county: "Kings County", match: ["brooklyn"], lines: [
      { name: "NYC Real Property Transfer Tax — commercial (all other transfers)", rate: 0.02625, tiers: [{ over: 0, rate: 0.01425 }, { over: 500000, rate: 0.02625 }], base: "price", party: "seller", source: S2, sourceUrl: S3, asOf: "2026-09-24", notes: "NYC DOF: 'All other transfers: If the value is $500,000 or less, the rate is 1.425% of the price. If the value is more than $500,000 the rate is 2.625%.' Cliff — the bracket rate applies to the WHOLE price. Grantor (seller) pays." },
      { name: "NYS additional base tax — NYC non-residential ≥ $2M (Tax Law §1402(b))", rate: 0.0025, tiers: [{ over: 0, rate: 0 }, { over: 1999999.99, rate: 0.0025 }], base: "price", party: "seller", source: S4, sourceUrl: S5, asOf: "2025-12-30", notes: "DTF: from 7/1/2019, 'An additional base tax of $1.25 for each $500 ... when the consideration for the entire conveyance of property other than residential real property is $2 million or more' (NYC only). Cliff at $2,000,000 on the whole consideration (modeled as over 1,999,999.99 because the test is '$2M or more'). Seller pays (same as base tax). With the 0.4% state base tax the state total in NYC is 0.65% on commercial ≥ $2M. The residential version starts at $3M and the residential 'supplemental' 0.25%–2.9% tax is residential-only (not modeled)." },
      { name: "Mortgage Recording Tax — NYC (commercial)", rate: 0.028, tiers: [{ over: 0, rate: 0.0205 }, { over: 499999.99, rate: 0.028 }], base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 4: all mortgages < $500,000 = $2.05/$100 (NYC 1.00 + basic 0.50 + special additional 0.25 + MCTD additional 0.30); 'All other mortgages securing $500,000 or more' = $2.80/$100 (NYC 1.75 + 0.50 + 0.25 + 0.30). Cliff on whole loan amount at $500,000 (modeled as over 499,999.99 because the test is '$500,000 or more'). (1–3 family / residential condo ≥$500K = 2.175%, not applicable.) Borrower pays on commercial." }
    ] },
  { id: "ny-lewis-county", kind: "county", name: "Lewis County", county: "Lewis County", lines: [
      { name: "Mortgage Recording Tax — Lewis (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-livingston-county", kind: "county", name: "Livingston County", county: "Livingston County", lines: [
      { name: "Mortgage Recording Tax — Livingston (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-madison-county", kind: "county", name: "Madison County", county: "Madison County", lines: [
      { name: "Mortgage Recording Tax — Madison (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." },
      { name: "Madison County real estate transfer tax", rate: 0.004, base: "price", party: "seller", source: S12, sourceUrl: S13, asOf: "2025-12-02", notes: "LL 5/2025 §5: 'For the period commencing December 2, 2025 and ending December 1, 2028 ... at the rate of two dollars for each five hundred dollars' (0.4% — same as the state rate, so Madison total = 0.8%). §7: 'shall be paid by the grantor.' Flat on whole consideration; exemptions are governmental/mere-change-of-form only. Sunsets 12/1/2028 unless extended." }
    ] },
  { id: "ny-monroe-county", kind: "county", name: "Monroe County", county: "Monroe County", lines: [
      { name: "Mortgage Recording Tax — Monroe (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-montgomery-county", kind: "county", name: "Montgomery County", county: "Montgomery County", lines: [
      { name: "Mortgage Recording Tax — Montgomery (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-nassau-county", kind: "county", name: "Nassau County", county: "Nassau County", lines: [
      { name: "Mortgage Recording Tax — Nassau (commercial)", rate: 0.0105, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.05% of principal debt (basic 0.50% + special additional 0.25% + MCTD additional 0.30%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-new-york-county", kind: "county", name: "New York County", county: "New York County", match: ["manhattan", "new york city"], lines: [
      { name: "NYC Real Property Transfer Tax — commercial (all other transfers)", rate: 0.02625, tiers: [{ over: 0, rate: 0.01425 }, { over: 500000, rate: 0.02625 }], base: "price", party: "seller", source: S2, sourceUrl: S3, asOf: "2026-09-24", notes: "NYC DOF: 'All other transfers: If the value is $500,000 or less, the rate is 1.425% of the price. If the value is more than $500,000 the rate is 2.625%.' Cliff — the bracket rate applies to the WHOLE price. Grantor (seller) pays." },
      { name: "NYS additional base tax — NYC non-residential ≥ $2M (Tax Law §1402(b))", rate: 0.0025, tiers: [{ over: 0, rate: 0 }, { over: 1999999.99, rate: 0.0025 }], base: "price", party: "seller", source: S4, sourceUrl: S5, asOf: "2025-12-30", notes: "DTF: from 7/1/2019, 'An additional base tax of $1.25 for each $500 ... when the consideration for the entire conveyance of property other than residential real property is $2 million or more' (NYC only). Cliff at $2,000,000 on the whole consideration (modeled as over 1,999,999.99 because the test is '$2M or more'). Seller pays (same as base tax). With the 0.4% state base tax the state total in NYC is 0.65% on commercial ≥ $2M. The residential version starts at $3M and the residential 'supplemental' 0.25%–2.9% tax is residential-only (not modeled)." },
      { name: "Mortgage Recording Tax — NYC (commercial)", rate: 0.028, tiers: [{ over: 0, rate: 0.0205 }, { over: 499999.99, rate: 0.028 }], base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 4: all mortgages < $500,000 = $2.05/$100 (NYC 1.00 + basic 0.50 + special additional 0.25 + MCTD additional 0.30); 'All other mortgages securing $500,000 or more' = $2.80/$100 (NYC 1.75 + 0.50 + 0.25 + 0.30). Cliff on whole loan amount at $500,000 (modeled as over 499,999.99 because the test is '$500,000 or more'). (1–3 family / residential condo ≥$500K = 2.175%, not applicable.) Borrower pays on commercial." }
    ] },
  { id: "ny-niagara-county", kind: "county", name: "Niagara County", county: "Niagara County", lines: [
      { name: "Mortgage Recording Tax — Niagara (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-oneida-county", kind: "county", name: "Oneida County", county: "Oneida County", lines: [
      { name: "Mortgage Recording Tax — Oneida (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-onondaga-county", kind: "county", name: "Onondaga County", county: "Onondaga County", lines: [
      { name: "Mortgage Recording Tax — Onondaga (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-ontario-county", kind: "county", name: "Ontario County", county: "Ontario County", lines: [
      { name: "Mortgage Recording Tax — Ontario (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-orange-county", kind: "county", name: "Orange County", county: "Orange County", lines: [
      { name: "Mortgage Recording Tax — Orange (commercial)", rate: 0.0105, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.05% of principal debt (basic 0.50% + special additional 0.25% + MCTD additional 0.30%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-orleans-county", kind: "county", name: "Orleans County", county: "Orleans County", lines: [
      { name: "Mortgage Recording Tax — Orleans (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-oswego-county", kind: "county", name: "Oswego County", county: "Oswego County", lines: [
      { name: "Mortgage Recording Tax — Oswego (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-otsego-county", kind: "county", name: "Otsego County", county: "Otsego County", lines: [
      { name: "Mortgage Recording Tax — Otsego (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-putnam-county", kind: "county", name: "Putnam County", county: "Putnam County", lines: [
      { name: "Mortgage Recording Tax — Putnam (commercial)", rate: 0.0105, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.05% of principal debt (basic 0.50% + special additional 0.25% + MCTD additional 0.30%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-queens-county", kind: "county", name: "Queens County", county: "Queens County", match: ["queens"], lines: [
      { name: "NYC Real Property Transfer Tax — commercial (all other transfers)", rate: 0.02625, tiers: [{ over: 0, rate: 0.01425 }, { over: 500000, rate: 0.02625 }], base: "price", party: "seller", source: S2, sourceUrl: S3, asOf: "2026-09-24", notes: "NYC DOF: 'All other transfers: If the value is $500,000 or less, the rate is 1.425% of the price. If the value is more than $500,000 the rate is 2.625%.' Cliff — the bracket rate applies to the WHOLE price. Grantor (seller) pays." },
      { name: "NYS additional base tax — NYC non-residential ≥ $2M (Tax Law §1402(b))", rate: 0.0025, tiers: [{ over: 0, rate: 0 }, { over: 1999999.99, rate: 0.0025 }], base: "price", party: "seller", source: S4, sourceUrl: S5, asOf: "2025-12-30", notes: "DTF: from 7/1/2019, 'An additional base tax of $1.25 for each $500 ... when the consideration for the entire conveyance of property other than residential real property is $2 million or more' (NYC only). Cliff at $2,000,000 on the whole consideration (modeled as over 1,999,999.99 because the test is '$2M or more'). Seller pays (same as base tax). With the 0.4% state base tax the state total in NYC is 0.65% on commercial ≥ $2M. The residential version starts at $3M and the residential 'supplemental' 0.25%–2.9% tax is residential-only (not modeled)." },
      { name: "Mortgage Recording Tax — NYC (commercial)", rate: 0.028, tiers: [{ over: 0, rate: 0.0205 }, { over: 499999.99, rate: 0.028 }], base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 4: all mortgages < $500,000 = $2.05/$100 (NYC 1.00 + basic 0.50 + special additional 0.25 + MCTD additional 0.30); 'All other mortgages securing $500,000 or more' = $2.80/$100 (NYC 1.75 + 0.50 + 0.25 + 0.30). Cliff on whole loan amount at $500,000 (modeled as over 499,999.99 because the test is '$500,000 or more'). (1–3 family / residential condo ≥$500K = 2.175%, not applicable.) Borrower pays on commercial." }
    ] },
  { id: "ny-rensselaer-county", kind: "county", name: "Rensselaer County", county: "Rensselaer County", lines: [
      { name: "Mortgage Recording Tax — Rensselaer (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-richmond-county", kind: "county", name: "Richmond County", county: "Richmond County", match: ["staten island"], lines: [
      { name: "NYC Real Property Transfer Tax — commercial (all other transfers)", rate: 0.02625, tiers: [{ over: 0, rate: 0.01425 }, { over: 500000, rate: 0.02625 }], base: "price", party: "seller", source: S2, sourceUrl: S3, asOf: "2026-09-24", notes: "NYC DOF: 'All other transfers: If the value is $500,000 or less, the rate is 1.425% of the price. If the value is more than $500,000 the rate is 2.625%.' Cliff — the bracket rate applies to the WHOLE price. Grantor (seller) pays." },
      { name: "NYS additional base tax — NYC non-residential ≥ $2M (Tax Law §1402(b))", rate: 0.0025, tiers: [{ over: 0, rate: 0 }, { over: 1999999.99, rate: 0.0025 }], base: "price", party: "seller", source: S4, sourceUrl: S5, asOf: "2025-12-30", notes: "DTF: from 7/1/2019, 'An additional base tax of $1.25 for each $500 ... when the consideration for the entire conveyance of property other than residential real property is $2 million or more' (NYC only). Cliff at $2,000,000 on the whole consideration (modeled as over 1,999,999.99 because the test is '$2M or more'). Seller pays (same as base tax). With the 0.4% state base tax the state total in NYC is 0.65% on commercial ≥ $2M. The residential version starts at $3M and the residential 'supplemental' 0.25%–2.9% tax is residential-only (not modeled)." },
      { name: "Mortgage Recording Tax — NYC (commercial)", rate: 0.028, tiers: [{ over: 0, rate: 0.0205 }, { over: 499999.99, rate: 0.028 }], base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 4: all mortgages < $500,000 = $2.05/$100 (NYC 1.00 + basic 0.50 + special additional 0.25 + MCTD additional 0.30); 'All other mortgages securing $500,000 or more' = $2.80/$100 (NYC 1.75 + 0.50 + 0.25 + 0.30). Cliff on whole loan amount at $500,000 (modeled as over 499,999.99 because the test is '$500,000 or more'). (1–3 family / residential condo ≥$500K = 2.175%, not applicable.) Borrower pays on commercial." }
    ] },
  { id: "ny-rockland-county", kind: "county", name: "Rockland County", county: "Rockland County", lines: [
      { name: "Mortgage Recording Tax — Rockland (commercial)", rate: 0.013, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.30% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.30% (MCTD)), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-saratoga-county", kind: "county", name: "Saratoga County", county: "Saratoga County", lines: [
      { name: "Mortgage Recording Tax — Saratoga (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-schenectady-county", kind: "county", name: "Schenectady County", county: "Schenectady County", lines: [
      { name: "Mortgage Recording Tax — Schenectady (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-schoharie-county", kind: "county", name: "Schoharie County", county: "Schoharie County", lines: [
      { name: "Mortgage Recording Tax — Schoharie (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-schuyler-county", kind: "county", name: "Schuyler County", county: "Schuyler County", lines: [
      { name: "Mortgage Recording Tax — Schuyler (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-seneca-county", kind: "county", name: "Seneca County", county: "Seneca County", lines: [
      { name: "Mortgage Recording Tax — Seneca (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-st-lawrence-county", kind: "county", name: "St. Lawrence County", county: "St. Lawrence County", lines: [
      { name: "Mortgage Recording Tax — St. Lawrence (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-steuben-county", kind: "county", name: "Steuben County", county: "Steuben County", lines: [
      { name: "Mortgage Recording Tax — Steuben (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-suffolk-county", kind: "county", name: "Suffolk County", county: "Suffolk County", lines: [
      { name: "Mortgage Recording Tax — Suffolk (commercial)", rate: 0.0105, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.05% of principal debt (basic 0.50% + special additional 0.25% + MCTD additional 0.30%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-sullivan-county", kind: "county", name: "Sullivan County", county: "Sullivan County", lines: [
      { name: "Mortgage Recording Tax — Sullivan (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-tioga-county", kind: "county", name: "Tioga County", county: "Tioga County", lines: [
      { name: "Mortgage Recording Tax — Tioga (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-tompkins-county", kind: "county", name: "Tompkins County", county: "Tompkins County", lines: [
      { name: "Mortgage Recording Tax — Tompkins (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." },
      { name: "Tompkins County real estate transfer tax", rate: 0.002, base: "price", party: "seller", source: S14, sourceUrl: S15, asOf: "2026-09-24", notes: "Tax Law §1449-bbbbb: '$1 for each $500'; county tax in effect since 12/1/2006. Paid by grantor (§1449-ddddd). Only threshold exemption is residential (<$200K personal residence option/contract)." }
    ] },
  { id: "ny-ulster-county", kind: "county", name: "Ulster County", county: "Ulster County", lines: [
      { name: "Mortgage Recording Tax — Ulster (commercial)", rate: 0.0075, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 0.75% of principal debt (basic 0.50% + special additional 0.25%; additional tax suspended in this county), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-warren-county", kind: "county", name: "Warren County", county: "Warren County", lines: [
      { name: "Mortgage Recording Tax — Warren (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-washington-county", kind: "county", name: "Washington County", county: "Washington County", lines: [
      { name: "Mortgage Recording Tax — Washington (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-wayne-county", kind: "county", name: "Wayne County", county: "Wayne County", lines: [
      { name: "Mortgage Recording Tax — Wayne (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-westchester-county", kind: "county", name: "Westchester County", county: "Westchester County", lines: [
      { name: "Mortgage Recording Tax — Westchester (commercial)", rate: 0.013, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.30% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.30% (MCTD)), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-wyoming-county", kind: "county", name: "Wyoming County", county: "Wyoming County", lines: [
      { name: "Mortgage Recording Tax — Wyoming (commercial)", rate: 0.0125, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.25% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25% + additional 0.25%), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-yates-county", kind: "county", name: "Yates County", county: "Yates County", lines: [
      { name: "Mortgage Recording Tax — Yates (commercial)", rate: 0.01, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "Total 1.00% of principal debt (county local 0.25% + basic 0.50% + special additional 0.25%; no additional tax), per MT-15 (1/25) rate tables. Commercial: the $10,000 / $25–$30 1-2 family residential deduction does NOT apply. Borrower customarily pays on commercial loans." }
    ] },
  { id: "ny-westchester-county-yonkers-city", kind: "municipal", name: "Yonkers city", county: "Westchester County", lines: [
      { name: "Yonkers city real estate transfer tax", rate: 0.015, tiers: [{ over: 0, rate: 0 }, { over: 25000, rate: 0.015 }], base: "price", party: "seller", source: S16, sourceUrl: S17, asOf: "2026-09-24", notes: "City: 'This tax is 1.5% of the selling price, and the seller is required to pay the tax ... No tax is required if a sale is $25,000 or less.' Cliff: above $25,000 the 1.5% applies to the whole price. Exemptions per Yonkers City Code §15-64(B)." },
      { name: "Mortgage Recording Tax — Yonkers city local tax (in addition to Westchester County line)", rate: 0.005, base: "loan", party: "buyer", source: S0, sourceUrl: S1, asOf: "2025-01-01", notes: "MT-15 Table 5: Yonkers (city) local tax $0.50/$100 on top of the Westchester County total $1.30 → Yonkers all-in 1.80% (the Westchester $0.25 county tax is included in the county line). Borrower pays on commercial." }
    ] },
  { id: "ny-westchester-county-mount-vernon-city", kind: "municipal", verify: "The 2/1/2026 change (1.5% above $50K) comes from the Comptroller's notice as hosted by a title company; the city's own return form agrees. Confirm.", name: "Mount Vernon city", county: "Westchester County", lines: [
      { name: "Mount Vernon city real property transfer tax", rate: 0.015, marginalTiers: [{ over: 0, rate: 0 }, { over: 50000, rate: 0.015 }], base: "price", party: "seller", source: S18, sourceUrl: S19, asOf: "2026-02-01", notes: "Comptroller: 1.5% 'of the consideration or value ... subject to applicable exemptions and deductions'; 'An exemption of up to $50,000'; worked example $600,000 − $50,000 = $550,000 × 1.5%. So a DEDUCTIBLE exemption (marginal). Applies by deed date ≥ 2/1/2026 regardless of contract date (was 1% with $100,000 exclusion before). City return: tax 'shall be paid by the Grantor' for contracts after 12/31/2000. Tax Law §1205 also lets the city deduct qualifying liens — not modeled." }
    ] },
  { id: "ny-westchester-county-peekskill-city", kind: "municipal", verify: "Source is a title-company-hosted copy of the city's transfer-tax form; the city's own page wasn't retrieved. Confirm.", name: "Peekskill city", county: "Westchester County", lines: [
      { name: "Peekskill city real property transfer tax", rate: 0.01, base: "price", party: "seller", source: S20, sourceUrl: S21, asOf: "2026-09-24", notes: "Form Section I: 'Tax due - 1% of line 1' (full consideration, no exclusion line). Tax Law §1206 caps at 1% and PERMITS (does not require) up to a $100,000 exemption — the city form applies none. Paid by grantor (deed delivered on/after 12/1/2010). Official city-hosted copy not retrieved — confirm with Peekskill Finance." }
    ] },
  { id: "ny-suffolk-county-east-hampton-town", kind: "municipal", name: "East Hampton town", county: "Suffolk County", match: ["amagansett", "east hampton", "montauk", "springs", "wainscott"], lines: [
      F0(0.025, "Tax Law Art. 31-D (§1449-bb). Form: '2% Community Preservation Fund' + '.5% Community Housing Fund EAST HAMPTON, SHELTER ISLAND, SOUTHAMPTON, SOUTHOLD' (CHF effective 4/1/2023). Allowances are 'Exemptions on Residential Property Only' (and none above $2,000,000), so COMMERCIAL pays 2.5% of the full consideration. Grantee (buyer) pays (Southold FAQ: 'paid by the grantee'). Villages inside the town (e.g. Sag Harbor, Greenport, Dering Harbor, Westhampton Beach) are included — Sag Harbor straddles East Hampton/Southampton, so it is not aliased.")
    ] },
  { id: "ny-suffolk-county-shelter-island-town", kind: "municipal", name: "Shelter Island town", county: "Suffolk County", match: ["shelter island", "shelter island heights"], lines: [
      F0(0.025, "Tax Law Art. 31-D (§1449-bb). Form: '2% Community Preservation Fund' + '.5% Community Housing Fund EAST HAMPTON, SHELTER ISLAND, SOUTHAMPTON, SOUTHOLD' (CHF effective 4/1/2023). Allowances are 'Exemptions on Residential Property Only' (and none above $2,000,000), so COMMERCIAL pays 2.5% of the full consideration. Grantee (buyer) pays (Southold FAQ: 'paid by the grantee'). Villages inside the town (e.g. Sag Harbor, Greenport, Dering Harbor, Westhampton Beach) are included — Sag Harbor straddles East Hampton/Southampton, so it is not aliased.")
    ] },
  { id: "ny-suffolk-county-southampton-town", kind: "municipal", name: "Southampton town", county: "Suffolk County", match: ["bridgehampton", "east quogue", "hampton bays", "quogue", "remsenburg", "sagaponack", "southampton", "water mill", "westhampton", "westhampton beach"], lines: [
      F0(0.025, "Tax Law Art. 31-D (§1449-bb). Form: '2% Community Preservation Fund' + '.5% Community Housing Fund EAST HAMPTON, SHELTER ISLAND, SOUTHAMPTON, SOUTHOLD' (CHF effective 4/1/2023). Allowances are 'Exemptions on Residential Property Only' (and none above $2,000,000), so COMMERCIAL pays 2.5% of the full consideration. Grantee (buyer) pays (Southold FAQ: 'paid by the grantee'). Villages inside the town (e.g. Sag Harbor, Greenport, Dering Harbor, Westhampton Beach) are included — Sag Harbor straddles East Hampton/Southampton, so it is not aliased.")
    ] },
  { id: "ny-suffolk-county-southold-town", kind: "municipal", name: "Southold town", county: "Suffolk County", match: ["cutchogue", "east marion", "greenport", "laurel", "mattituck", "new suffolk", "orient", "peconic", "southold"], lines: [
      F0(0.025, "Tax Law Art. 31-D (§1449-bb). Form: '2% Community Preservation Fund' + '.5% Community Housing Fund EAST HAMPTON, SHELTER ISLAND, SOUTHAMPTON, SOUTHOLD' (CHF effective 4/1/2023). Allowances are 'Exemptions on Residential Property Only' (and none above $2,000,000), so COMMERCIAL pays 2.5% of the full consideration. Grantee (buyer) pays (Southold FAQ: 'paid by the grantee'). Villages inside the town (e.g. Sag Harbor, Greenport, Dering Harbor, Westhampton Beach) are included — Sag Harbor straddles East Hampton/Southampton, so it is not aliased.")
    ] },
  { id: "ny-suffolk-county-riverhead-town", kind: "municipal", name: "Riverhead town", county: "Suffolk County", match: ["aquebogue", "jamesport", "riverhead"], lines: [
      { name: "Peconic Bay Region CPF 2% (Riverhead — no housing supplement)", rate: 0.02, marginalTiers: [{ over: 0, rate: 0 }, { over: 150000, rate: 0.02 }], base: "price", party: "buyer", source: S22, sourceUrl: S23, asOf: "2023-04-01", notes: "Form: Riverhead 'Exemptions on Residential and Commercial Property' — $150,000 improved / $75,000 vacant land deducted from consideration, then 2%. Riverhead did NOT adopt the 0.5% Community Housing Fund. Modeled for IMPROVED property ($150K allowance); vacant land uses $75K. Grantee (buyer) pays." }
    ] },
  { id: "ny-orange-county-warwick-town", kind: "municipal", name: "Warwick town", county: "Orange County", match: ["greenwood lake", "pine island", "warwick"], lines: [
      { name: "Town of Warwick Community Preservation Fund transfer tax", rate: 0.0075, marginalTiers: [{ over: 0, rate: 0 }, { over: 100000, rate: 0.0075 }], base: "price", party: "buyer", source: S24, sourceUrl: S25, asOf: "2026-09-24", notes: "Form: 'Allowance (Improved property - $100,000; Vacant land - $50,000)' deducted, then '0.75 % Community Preservation Fund (of line 3)'. Applies to all property types. Tax Law §1449-dddd: 'shall be paid by the grantee'. Includes villages of Warwick, Greenwood Lake and Florida. Art. 31-F repealed 12/31/2050. Modeled for improved property." }
    ] },
  { id: "ny-dutchess-county-red-hook-town", kind: "municipal", name: "Red Hook town", county: "Dutchess County", match: ["red hook", "tivoli"], lines: [
      { name: "Town of Red Hook Community Preservation Fund transfer tax", rate: 0.02, marginalTiers: [{ over: 0, rate: 0 }, { over: 475000, rate: 0.02 }], base: "price", party: "buyer", source: S26, sourceUrl: S27, asOf: "2026-04-21", notes: "Form: taxable = consideration − 'median sales price of residential real property in Dutchess County'; 'Multiply line 3 ... x 2%'. Clerk: 'Enter $475,000 (on or After April 21st, 2026)' (matches NYS DTF 2025 Dutchess median $475,000). Applies to all property types. Buyer pays. Includes villages of Red Hook and Tivoli. Median resets annually — re-verify." }
    ] },
  { id: "ny-ulster-county-kingston-city", kind: "municipal", name: "Kingston city", county: "Ulster County", match: ["kingston"], lines: [
      { name: "Kingston Community Preservation Fund transfer tax", rate: 0.0125, marginalTiers: [{ over: 0, rate: 0 }, { over: 437000, rate: 0.0125 }], base: "price", party: "buyer", source: S28, sourceUrl: S29, asOf: "2026-04-23", notes: "City of Kingston LL 10 of 2024 (§188-12 'shall be paid by the buyer'; §188-14 median exemption 'on the consideration of the conveyance of improved or unimproved real property'), effective 12/15/2024. NOTE: the local law text says the median 'within the City of Kingston', but the County Clerk instructs filers to enter the Ulster County median — clerk practice used here. Exemption = Ulster County residential median sale price as determined by NYS DTF — $437,000 on/after 4/23/2026 ($425,000 before). Clerk form Schedule B: taxable = consideration − median; applies to ALL property types (commercial included). Grantee (buyer) pays; seller liable if buyer fails. Median resets annually (~April) — re-verify." }
    ] },
  { id: "ny-ulster-county-gardiner-town", kind: "municipal", name: "Gardiner town", county: "Ulster County", match: ["gardiner"], lines: [
      { name: "Gardiner Community Preservation Fund transfer tax", rate: 0.0125, marginalTiers: [{ over: 0, rate: 0 }, { over: 437000, rate: 0.0125 }], base: "price", party: "buyer", source: S28, sourceUrl: S29, asOf: "2026-04-23", notes: "Town of Gardiner LL 5 of 2022, effective 2/1/2023; form: 'x 1.25% (.0125)'. Exemption = Ulster County residential median sale price as determined by NYS DTF — $437,000 on/after 4/23/2026 ($425,000 before). Clerk form Schedule B: taxable = consideration − median; applies to ALL property types (commercial included). Grantee (buyer) pays; seller liable if buyer fails. Median resets annually (~April) — re-verify." }
    ] },
  { id: "ny-ulster-county-marbletown-town", kind: "municipal", name: "Marbletown town", county: "Ulster County", match: ["high falls", "stone ridge"], lines: [
      { name: "Marbletown Community Preservation Fund transfer tax", rate: 0.01, marginalTiers: [{ over: 0, rate: 0 }, { over: 437000, rate: 0.01 }], base: "price", party: "buyer", source: S28, sourceUrl: S29, asOf: "2026-04-23", notes: "Town of Marbletown LL 6 of 2022, effective 1/1/2023; form: 'x 1% (.01)'. Exemption = Ulster County residential median sale price as determined by NYS DTF — $437,000 on/after 4/23/2026 ($425,000 before). Clerk form Schedule B: taxable = consideration − median; applies to ALL property types (commercial included). Grantee (buyer) pays; seller liable if buyer fails. Median resets annually (~April) — re-verify." }
    ] },
  { id: "ny-ulster-county-new-paltz-town", kind: "municipal", name: "New Paltz town", county: "Ulster County", match: ["new paltz"], lines: [
      { name: "New Paltz Community Preservation Fund transfer tax", rate: 0.015, marginalTiers: [{ over: 0, rate: 0 }, { over: 437000, rate: 0.015 }], base: "price", party: "buyer", source: S28, sourceUrl: S29, asOf: "2026-04-23", notes: "Town of New Paltz LL 5 of 2020, effective 2/1/2021 (town AND village of New Paltz); form: 'x 1.5% (.015)'. Exemption = Ulster County residential median sale price as determined by NYS DTF — $437,000 on/after 4/23/2026 ($425,000 before). Clerk form Schedule B: taxable = consideration − median; applies to ALL property types (commercial included). Grantee (buyer) pays; seller liable if buyer fails. Median resets annually (~April) — re-verify." }
    ] },
  { id: "ny-ulster-county-rochester-town", kind: "municipal", name: "Rochester town", county: "Ulster County", match: ["accord", "kerhonkson"], lines: [
      { name: "Rochester Community Preservation Fund transfer tax", rate: 0.01, marginalTiers: [{ over: 0, rate: 0 }, { over: 437000, rate: 0.01 }], base: "price", party: "buyer", source: S28, sourceUrl: S29, asOf: "2026-04-23", notes: "Town of Rochester LL 6 of 2025, effective 2/1/2026; form: 'x 1% (.01)'. Exemption = Ulster County residential median sale price as determined by NYS DTF — $437,000 on/after 4/23/2026 ($425,000 before). Clerk form Schedule B: taxable = consideration − median; applies to ALL property types (commercial included). Grantee (buyer) pays; seller liable if buyer fails. Median resets annually (~April) — re-verify." }
    ] },
  { id: "ny-columbia-county-chatham-town", kind: "municipal", verify: "Exemption threshold ($485K = 2025 Columbia County median) not confirmed — town pages still show 2024 figures.", name: "Chatham town", county: "Columbia County", lines: [
      { name: "Town of Chatham Community Preservation Fund transfer tax", rate: 0.015, marginalTiers: [{ over: 0, rate: 0 }, { over: 485000, rate: 0.015 }], base: "price", party: "buyer", verify: true, source: S30, sourceUrl: S31, asOf: "2024-02-01", notes: "1.5% on consideration above the Columbia County residential median (buyer pays; effective 2/1/2024). Town page example uses $375,000; County Clerk page says $370,000 'for 2024'. NYS DTF's published Columbia 2025 median is $485,000, which is presumably the exemption now in use — NOT confirmed by the clerk/town; verify before relying. Modeled at $485,000. Exemption threshold ($485K = 2025 Columbia County median) NOT confirmed — town pages still show 2024 figures." }
    ] },
  ],
};
