import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiRouter from "./ai";
import authRouter from "./auth";
import dealsRouter from "./deals";
import ingestRouter from "./ingest";
import aliasesRouter from "./aliases";
import tenantDecisionsRouter from "./tenantDecisions";
import tenantIndexRouter from "./tenantIndex";
import analyticsRouter from "./analytics";
import compsRouter from "./comps";
import watchlistRouter from "./watchlist";
import closingRouter from "./closing";
import snapshotsRouter from "./snapshots";
import feedbackRouter from "./feedback";
import clientErrorsRouter from "./clientErrors";
import ratesRouter from "./rates";
import uploadLogRouter from "./uploadLog";
import extractionLessonsRouter from "./extractionLessons";
import leaseAbstractsRouter from "./leaseAbstracts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(ingestRouter);
router.use(dealsRouter);
router.use(aliasesRouter);
router.use(tenantDecisionsRouter);
router.use(tenantIndexRouter);
router.use(analyticsRouter);
router.use(compsRouter);
router.use(watchlistRouter);
router.use(closingRouter);
router.use(snapshotsRouter);
router.use(feedbackRouter);
router.use(clientErrorsRouter);
router.use(ratesRouter);
router.use(uploadLogRouter);
router.use(extractionLessonsRouter);
router.use(leaseAbstractsRouter);
router.use(aiRouter);

export default router;
